### ISSUE TITLE
failed ensure does not show why (unlike Xebium)

### ISSUE THREAD

**Issue by sglebs** [fhoeben/hsac-xebium-bridge#6]
Hi @fhoeben 

My friend is seeing this test fail under chrome both under Xebium and under hsac-Xebium. So, he wanted to troubleshoot why. With hsac-Xebium he only sees this is the output:

```
| ensure    | do    | click | on | //div[@id='empresa_grupo']/span/span | screenshot-here |
```

Your bridge paints "ensure" in red and that's it. No idea why.

On the other hand, running under pure/original Xebium, he sees this:

```
| ensure    | do    | click | on | //div[@id='empresa_grupo']/span/span | screenshot-here |

__EXCEPTION__:java.lang.AssertionError: com.thoughtworks.selenium.SeleniumException: element not visible
 (Session info: chrome=43.0.2357.81)
 (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 21 milliseconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'ENG023', ip: '192.168.200.51', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_67'
Session ID: 43796711289c7a2cc32007f0c0d79eed
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\EDSON~1.SAK\AppData\Local\Temp\scoped_dir4308_25096}, rotatable=false, locationContextEnabled=true, version=43.0.2357.81, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.executeDoCommand(SeleniumDriverFixture.java:485) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.doOn(SeleniumDriverFixture.java:341) [xebium-0.15-SNAPSHOT-mqm.jar]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_67]
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_67]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_67]
 at java.lang.reflect.Method.invoke(Unknown Source) [rt.jar:1.7.0_67]
 at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:16) [fitnesse-standalone.jar]
 at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:43) [fitnesse-standalone.jar]
 at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:30) [fitnesse-standalone.jar]
 at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:52) [fitnesse-standalone.jar]
 at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20) [fitnesse-standalone.jar]
 at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:121) [fitnesse-standalone.jar]
 at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:99) [fitnesse-standalone.jar]
 at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-standalone.jar]
 at fitnesse.slim.instructions.Instruction.execute(Instruction.java:30) [fitnesse-standalone.jar]
 at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:50) [fitnesse-standalone.jar]
 at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:44) [fitnesse-standalone.jar]
 at fitnesse.slim.ListExecutor.execute(ListExecutor.java:84) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:106) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.processTheInstructions(SlimServer.java:93) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:68) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:54) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.serve(SlimServer.java:40) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.handle(SlimService.java:164) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.acceptOne(SlimService.java:172) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.accept(SlimService.java:134) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.startWithFactory(SlimService.java:65) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.main(SlimService.java:51) [fitnesse-standalone.jar]
Caused by: com.thoughtworks.selenium.SeleniumException: element not visible
 (Session info: chrome=43.0.2357.81)
 (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 21 milliseconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'ENG023', ip: '192.168.200.51', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_67'
Session ID: 43796711289c7a2cc32007f0c0d79eed
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\EDSON~1.SAK\AppData\Local\Temp\scoped_dir4308_25096}, rotatable=false, locationContextEnabled=true, version=43.0.2357.81, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
 at com.thoughtworks.selenium.webdriven.SeleneseCommand.apply(SeleneseCommand.java:44) [selenium-leg-rc-2.45.0.jar]
 at com.thoughtworks.selenium.webdriven.Timer.run(Timer.java:40) [selenium-leg-rc-2.45.0.jar]
 at com.thoughtworks.selenium.webdriven.WebDriverCommandProcessor.execute(WebDriverCommandProcessor.java:148) [selenium-leg-rc-2.45.0.jar]
 at com.thoughtworks.selenium.webdriven.WebDriverCommandProcessor.doCommand(WebDriverCommandProcessor.java:73) [selenium-leg-rc-2.45.0.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.executeCommand(SeleniumDriverFixture.java:592) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.getCommandOutput(SeleniumDriverFixture.java:559) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.executeCommand(SeleniumDriverFixture.java:540) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.executeAndCheckResult(SeleniumDriverFixture.java:508) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.executeDoCommand(SeleniumDriverFixture.java:466) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.doOn(SeleniumDriverFixture.java:341) [xebium-0.15-SNAPSHOT-mqm.jar]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_67]
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_67]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_67]
 at java.lang.reflect.Method.invoke(Unknown Source) [rt.jar:1.7.0_67]
 at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:16) [fitnesse-standalone.jar]
 at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:43) [fitnesse-standalone.jar]
 at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:30) [fitnesse-standalone.jar]
 at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:52) [fitnesse-standalone.jar]
 at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20) [fitnesse-standalone.jar]
 at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:121) [fitnesse-standalone.jar]
 at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:99) [fitnesse-standalone.jar]
 at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-standalone.jar]
 at fitnesse.slim.instructions.Instruction.execute(Instruction.java:30) [fitnesse-standalone.jar]
 at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:50) [fitnesse-standalone.jar]
 at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:44) [fitnesse-standalone.jar]
 at fitnesse.slim.ListExecutor.execute(ListExecutor.java:84) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:106) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.processTheInstructions(SlimServer.java:93) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:68) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:54) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.serve(SlimServer.java:40) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.handle(SlimService.java:164) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.acceptOne(SlimService.java:172) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.accept(SlimService.java:134) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.startWithFactory(SlimService.java:65) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.main(SlimService.java:51) [fitnesse-standalone.jar]
Caused by: org.openqa.selenium.ElementNotVisibleException: element not visible
 (Session info: chrome=43.0.2357.81)
 (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 21 milliseconds
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'ENG023', ip: '192.168.200.51', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_67'
Session ID: 43796711289c7a2cc32007f0c0d79eed
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=XP, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=C:\Users\EDSON~1.SAK\AppData\Local\Temp\scoped_dir4308_25096}, rotatable=false, locationContextEnabled=true, version=43.0.2357.81, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
 at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.7.0_67]
 at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [rt.jar:1.7.0_67]
 at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [rt.jar:1.7.0_67]
 at java.lang.reflect.Constructor.newInstance(Unknown Source) [rt.jar:1.7.0_67]
 at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204) [selenium-remote-driver-2.45.0.jar]
 at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156) [selenium-remote-driver-2.45.0.jar]
 at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599) [selenium-remote-driver-2.45.0.jar]
 at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268) [selenium-remote-driver-2.45.0.jar]
 at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:79) [selenium-remote-driver-2.45.0.jar]
 at com.thoughtworks.selenium.webdriven.commands.Click.handleSeleneseCommand(Click.java:39) [selenium-leg-rc-2.45.0.jar]
 at com.thoughtworks.selenium.webdriven.commands.Click.handleSeleneseCommand(Click.java:25) [selenium-leg-rc-2.45.0.jar]
 at com.thoughtworks.selenium.webdriven.SeleneseCommand.apply(SeleneseCommand.java:35) [selenium-leg-rc-2.45.0.jar]
 at com.thoughtworks.selenium.webdriven.Timer.run(Timer.java:40) [selenium-leg-rc-2.45.0.jar]
 at com.thoughtworks.selenium.webdriven.WebDriverCommandProcessor.execute(WebDriverCommandProcessor.java:148) [selenium-leg-rc-2.45.0.jar]
 at com.thoughtworks.selenium.webdriven.WebDriverCommandProcessor.doCommand(WebDriverCommandProcessor.java:73) [selenium-leg-rc-2.45.0.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.executeCommand(SeleniumDriverFixture.java:592) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.getCommandOutput(SeleniumDriverFixture.java:559) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.executeCommand(SeleniumDriverFixture.java:540) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.executeAndCheckResult(SeleniumDriverFixture.java:508) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.executeDoCommand(SeleniumDriverFixture.java:466) [xebium-0.15-SNAPSHOT-mqm.jar]
 at com.xebia.incubator.xebium.SeleniumDriverFixture.doOn(SeleniumDriverFixture.java:341) [xebium-0.15-SNAPSHOT-mqm.jar]
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_67]
 at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_67]
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) [rt.jar:1.7.0_67]
 at java.lang.reflect.Method.invoke(Unknown Source) [rt.jar:1.7.0_67]
 at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:16) [fitnesse-standalone.jar]
 at fitnesse.slim.MethodExecutor.callMethod(MethodExecutor.java:43) [fitnesse-standalone.jar]
 at fitnesse.slim.MethodExecutor.invokeMethod(MethodExecutor.java:30) [fitnesse-standalone.jar]
 at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:52) [fitnesse-standalone.jar]
 at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:20) [fitnesse-standalone.jar]
 at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:121) [fitnesse-standalone.jar]
 at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:99) [fitnesse-standalone.jar]
 at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-standalone.jar]
 at fitnesse.slim.instructions.Instruction.execute(Instruction.java:30) [fitnesse-standalone.jar]
 at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:50) [fitnesse-standalone.jar]
 at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:44) [fitnesse-standalone.jar]
 at fitnesse.slim.ListExecutor.execute(ListExecutor.java:84) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:106) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.processTheInstructions(SlimServer.java:93) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:68) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:54) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimServer.serve(SlimServer.java:40) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.handle(SlimService.java:164) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.acceptOne(SlimService.java:172) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.accept(SlimService.java:134) [fitnesse-standalone.jar]
 at fitnesse.slim.SlimService.startWithFactory(SlimService.java:65) [fitnesse-standalone.jar]



 at fitnesse.slim.SlimService.main(SlimService.java:51) [fitnesse-standalone.jar]

```

Is there anything I should/could do to have the exception or (better) the cause of the failure (java.lang.AssertionError: com.thoughtworks.selenium.SeleniumException: element not visible) to be displayed?

Thanks!

**Comment by fhoeben** [comment]
If you want the exception, use `HsacBasicSeleniumDriverFixture` that will give you real Xebium behavior in all of these things.
The fact that click returns false is taken from BrowserTest and intentional: when an element can be found and clicked true is returned, if it can not be clicked (for instance because it is not visible or not enabled false is returned)
